services:
  postgres:
    image: postgres
    volumes:
      - ./infra/migrations/ExecuteInsert.sh:/migration/ExecuteInsert.sh
      - ./infra/migrations/InsertInitialProducts.sql:/migration/InsertInitialProducts.sql
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    